server.port=8081
EXIST_BASE_URI=xmldb:exist://localhost:8080/exist/xmlrpc
EXIST_USER=admin
EXIST_PASSWORD=98qwaszx
EXIST_BASE_NAMESPACE=http://red-social.org/
EXIST_USER_PROFILE_PATH=/db/apps/red-social/perfilesUsuarios
EXIST_POST_PATH=/db/apps/red-social/posts
EXIST_BASE_SCHEMA_URI=xmldb:exist:///db/apps/red-social/esquemas/